### ISSUE TITLE
Multiple issues in Timesheet page

### ISSUE THREAD

**Issue by Shruthi0109** [CZ-App-Studio/cygnuz-erp#21]
**Describe the bug**

1. Editing a timesheet entry leads to a 403 error, even though the user has been granted permissions.
2. The deleting draft timesheet throws error popup message.
3. Searching a timesheet throws a DataTable warning.
4. In filters, the dropdown list for users and projects is not available.

**Steps to reproduce the behavior:**
1. Navigate to Timesheet
2. Try editing an existing timesheet entry.
            - A 403 error is displayed.
3. Try deleting a timesheet entry which is in draft.
            - The delete function throws error
4.Use the search bar to search for a timesheet entry.
            - A DataTable warning is displayed.
5.Open the filters and check the dropdowns for users and projects.
            - Dropdown lists are not available.

**Screenshots**
403 error:

<img width="1920" height="972" alt="Image" src="https://github.com/user-attachments/assets/39af27e0-0eb8-4a29-9748-8a6a3e070364" />

Deleting Draft Timesheet:

<img width="1920" height="924" alt="Image" src="https://github.com/user-attachments/assets/245fbd49-c802-434b-b03c-287961096f60" />

Datatable warning error:

<img width="1918" height="979" alt="Image" src="https://github.com/user-attachments/assets/c4b116c0-b36e-4361-bd23-3ca2f90329e3" />

**Module:**
 - Module Name: Project Management

**Comment by rmanoop25** [comment]
@Shruthi0109 issue is fixed check and let me know

**Comment by Shruthi0109** [comment]
@rmanoop25 Only the search function and the user's dropdown in filters are working. Other bugs are still not fixed, including the project dropdown in filters.
